version: '3.0'

services:

  google-street:
    container_name: google-street
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3006:3006'
    environment:
      - NODE_ENV=development